# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mav_msgs/System_pose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class System_pose(genpy.Message):
  _md5sum = "ebb248f942d8dda28943911c5ba3abb3"
  _type = "mav_msgs/System_pose"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

geometry_msgs/Pose uav1
geometry_msgs/Vector3 uav1_acc
geometry_msgs/Pose uav2
geometry_msgs/Vector3 uav2_acc
geometry_msgs/Pose uav3
geometry_msgs/Vector3 uav3_acc
geometry_msgs/Pose uav4
geometry_msgs/Vector3 uav4_acc
geometry_msgs/Pose payload
geometry_msgs/Vector3 payload_W
geometry_msgs/Vector3 payload_acc
geometry_msgs/Vector3 payload_vel
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','uav1','uav1_acc','uav2','uav2_acc','uav3','uav3_acc','uav4','uav4_acc','payload','payload_W','payload_acc','payload_vel']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,uav1,uav1_acc,uav2,uav2_acc,uav3,uav3_acc,uav4,uav4_acc,payload,payload_W,payload_acc,payload_vel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(System_pose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav1 is None:
        self.uav1 = geometry_msgs.msg.Pose()
      if self.uav1_acc is None:
        self.uav1_acc = geometry_msgs.msg.Vector3()
      if self.uav2 is None:
        self.uav2 = geometry_msgs.msg.Pose()
      if self.uav2_acc is None:
        self.uav2_acc = geometry_msgs.msg.Vector3()
      if self.uav3 is None:
        self.uav3 = geometry_msgs.msg.Pose()
      if self.uav3_acc is None:
        self.uav3_acc = geometry_msgs.msg.Vector3()
      if self.uav4 is None:
        self.uav4 = geometry_msgs.msg.Pose()
      if self.uav4_acc is None:
        self.uav4_acc = geometry_msgs.msg.Vector3()
      if self.payload is None:
        self.payload = geometry_msgs.msg.Pose()
      if self.payload_W is None:
        self.payload_W = geometry_msgs.msg.Vector3()
      if self.payload_acc is None:
        self.payload_acc = geometry_msgs.msg.Vector3()
      if self.payload_vel is None:
        self.payload_vel = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.uav1 = geometry_msgs.msg.Pose()
      self.uav1_acc = geometry_msgs.msg.Vector3()
      self.uav2 = geometry_msgs.msg.Pose()
      self.uav2_acc = geometry_msgs.msg.Vector3()
      self.uav3 = geometry_msgs.msg.Pose()
      self.uav3_acc = geometry_msgs.msg.Vector3()
      self.uav4 = geometry_msgs.msg.Pose()
      self.uav4_acc = geometry_msgs.msg.Vector3()
      self.payload = geometry_msgs.msg.Pose()
      self.payload_W = geometry_msgs.msg.Vector3()
      self.payload_acc = geometry_msgs.msg.Vector3()
      self.payload_vel = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_56d().pack(_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav1_acc.x, _x.uav1_acc.y, _x.uav1_acc.z, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav2_acc.x, _x.uav2_acc.y, _x.uav2_acc.z, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav3_acc.x, _x.uav3_acc.y, _x.uav3_acc.z, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.uav4_acc.x, _x.uav4_acc.y, _x.uav4_acc.z, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w, _x.payload_W.x, _x.payload_W.y, _x.payload_W.z, _x.payload_acc.x, _x.payload_acc.y, _x.payload_acc.z, _x.payload_vel.x, _x.payload_vel.y, _x.payload_vel.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav1 is None:
        self.uav1 = geometry_msgs.msg.Pose()
      if self.uav1_acc is None:
        self.uav1_acc = geometry_msgs.msg.Vector3()
      if self.uav2 is None:
        self.uav2 = geometry_msgs.msg.Pose()
      if self.uav2_acc is None:
        self.uav2_acc = geometry_msgs.msg.Vector3()
      if self.uav3 is None:
        self.uav3 = geometry_msgs.msg.Pose()
      if self.uav3_acc is None:
        self.uav3_acc = geometry_msgs.msg.Vector3()
      if self.uav4 is None:
        self.uav4 = geometry_msgs.msg.Pose()
      if self.uav4_acc is None:
        self.uav4_acc = geometry_msgs.msg.Vector3()
      if self.payload is None:
        self.payload = geometry_msgs.msg.Pose()
      if self.payload_W is None:
        self.payload_W = geometry_msgs.msg.Vector3()
      if self.payload_acc is None:
        self.payload_acc = geometry_msgs.msg.Vector3()
      if self.payload_vel is None:
        self.payload_vel = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 448
      (_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav1_acc.x, _x.uav1_acc.y, _x.uav1_acc.z, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav2_acc.x, _x.uav2_acc.y, _x.uav2_acc.z, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav3_acc.x, _x.uav3_acc.y, _x.uav3_acc.z, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.uav4_acc.x, _x.uav4_acc.y, _x.uav4_acc.z, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w, _x.payload_W.x, _x.payload_W.y, _x.payload_W.z, _x.payload_acc.x, _x.payload_acc.y, _x.payload_acc.z, _x.payload_vel.x, _x.payload_vel.y, _x.payload_vel.z,) = _get_struct_56d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_56d().pack(_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav1_acc.x, _x.uav1_acc.y, _x.uav1_acc.z, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav2_acc.x, _x.uav2_acc.y, _x.uav2_acc.z, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav3_acc.x, _x.uav3_acc.y, _x.uav3_acc.z, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.uav4_acc.x, _x.uav4_acc.y, _x.uav4_acc.z, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w, _x.payload_W.x, _x.payload_W.y, _x.payload_W.z, _x.payload_acc.x, _x.payload_acc.y, _x.payload_acc.z, _x.payload_vel.x, _x.payload_vel.y, _x.payload_vel.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav1 is None:
        self.uav1 = geometry_msgs.msg.Pose()
      if self.uav1_acc is None:
        self.uav1_acc = geometry_msgs.msg.Vector3()
      if self.uav2 is None:
        self.uav2 = geometry_msgs.msg.Pose()
      if self.uav2_acc is None:
        self.uav2_acc = geometry_msgs.msg.Vector3()
      if self.uav3 is None:
        self.uav3 = geometry_msgs.msg.Pose()
      if self.uav3_acc is None:
        self.uav3_acc = geometry_msgs.msg.Vector3()
      if self.uav4 is None:
        self.uav4 = geometry_msgs.msg.Pose()
      if self.uav4_acc is None:
        self.uav4_acc = geometry_msgs.msg.Vector3()
      if self.payload is None:
        self.payload = geometry_msgs.msg.Pose()
      if self.payload_W is None:
        self.payload_W = geometry_msgs.msg.Vector3()
      if self.payload_acc is None:
        self.payload_acc = geometry_msgs.msg.Vector3()
      if self.payload_vel is None:
        self.payload_vel = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 448
      (_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav1_acc.x, _x.uav1_acc.y, _x.uav1_acc.z, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav2_acc.x, _x.uav2_acc.y, _x.uav2_acc.z, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav3_acc.x, _x.uav3_acc.y, _x.uav3_acc.z, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.uav4_acc.x, _x.uav4_acc.y, _x.uav4_acc.z, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w, _x.payload_W.x, _x.payload_W.y, _x.payload_W.z, _x.payload_acc.x, _x.payload_acc.y, _x.payload_acc.z, _x.payload_vel.x, _x.payload_vel.y, _x.payload_vel.z,) = _get_struct_56d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_56d = None
def _get_struct_56d():
    global _struct_56d
    if _struct_56d is None:
        _struct_56d = struct.Struct("<56d")
    return _struct_56d
