
classdef PolygonServiceRequest < ros.Message
    %PolygonServiceRequest MATLAB implementation of mav_planning_msgs/PolygonServiceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_planning_msgs/PolygonServiceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b72bf7542ebf0f998ff6de9ed6f90873' % The MD5 Checksum of the message definition
        PropertyList = { 'Polygon' } % List of non-constant message properties
        ROSPropertyList = { 'polygon' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.mav_planning_msgs.PolygonWithHolesStamped' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Polygon
    end
    methods
        function set.Polygon(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.mav_planning_msgs.PolygonWithHolesStamped'};
            validateattributes(val, validClasses, validAttributes, 'PolygonServiceRequest', 'Polygon')
            obj.Polygon = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_planning_msgs.PolygonServiceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_planning_msgs.PolygonServiceRequest(strObj);
        end
    end
end
