
classdef Polygon2D < ros.Message
    %Polygon2D MATLAB implementation of mav_planning_msgs/Polygon2D
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_planning_msgs/Polygon2D' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8f02263beef99aa03117a577a3eb879d' % The MD5 Checksum of the message definition
        PropertyList = { 'Points' } % List of non-constant message properties
        ROSPropertyList = { 'points' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.mav_planning_msgs.Point2D' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Points
    end
    methods
        function set.Points(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.mav_planning_msgs.Point2D.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.mav_planning_msgs.Point2D'};
            validateattributes(val, validClasses, validAttributes, 'Polygon2D', 'Points')
            obj.Points = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_planning_msgs.Polygon2D.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_planning_msgs.Polygon2D(strObj);
        end
    end
end
