
classdef System_pose < ros.Message
    %System_pose MATLAB implementation of mav_msgs/System_pose
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/System_pose' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ebb248f942d8dda28943911c5ba3abb3' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Uav1' 'Uav1Acc' 'Uav2' 'Uav2Acc' 'Uav3' 'Uav3Acc' 'Uav4' 'Uav4Acc' 'Payload' 'PayloadW' 'PayloadAcc' 'PayloadVel' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'uav1' 'uav1_acc' 'uav2' 'uav2_acc' 'uav3' 'uav3_acc' 'uav4' 'uav4_acc' 'payload' 'payload_W' 'payload_acc' 'payload_vel' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Uav1
        Uav1Acc
        Uav2
        Uav2Acc
        Uav3
        Uav3Acc
        Uav4
        Uav4Acc
        Payload
        PayloadW
        PayloadAcc
        PayloadVel
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Header')
            obj.Header = val;
        end
        function set.Uav1(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav1')
            obj.Uav1 = val;
        end
        function set.Uav1Acc(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav1Acc')
            obj.Uav1Acc = val;
        end
        function set.Uav2(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav2')
            obj.Uav2 = val;
        end
        function set.Uav2Acc(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav2Acc')
            obj.Uav2Acc = val;
        end
        function set.Uav3(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav3')
            obj.Uav3 = val;
        end
        function set.Uav3Acc(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav3Acc')
            obj.Uav3Acc = val;
        end
        function set.Uav4(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav4')
            obj.Uav4 = val;
        end
        function set.Uav4Acc(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav4Acc')
            obj.Uav4Acc = val;
        end
        function set.Payload(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Payload')
            obj.Payload = val;
        end
        function set.PayloadW(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'PayloadW')
            obj.PayloadW = val;
        end
        function set.PayloadAcc(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'PayloadAcc')
            obj.PayloadAcc = val;
        end
        function set.PayloadVel(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'PayloadVel')
            obj.PayloadVel = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.System_pose.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.System_pose(strObj);
        end
    end
end
