
classdef ProcessInfo < ros.Message
    %ProcessInfo MATLAB implementation of mav_system_msgs/ProcessInfo
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_system_msgs/ProcessInfo' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e230da576ecad86012b88749ce2ed125' % The MD5 Checksum of the message definition
        PropertyList = { 'Pid' 'Name' 'Username' 'CpuPercent' } % List of non-constant message properties
        ROSPropertyList = { 'pid' 'name' 'username' 'cpu_percent' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pid
        Name
        Username
        CpuPercent
    end
    methods
        function set.Pid(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ProcessInfo', 'Pid');
            obj.Pid = uint32(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ProcessInfo', 'Name');
            obj.Name = char(val);
        end
        function set.Username(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ProcessInfo', 'Username');
            obj.Username = char(val);
        end
        function set.CpuPercent(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ProcessInfo', 'CpuPercent');
            obj.CpuPercent = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_system_msgs.ProcessInfo.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_system_msgs.ProcessInfo(strObj);
        end
    end
end
