
classdef RateThrust < ros.Message
    %RateThrust MATLAB implementation of mav_msgs/RateThrust
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/RateThrust' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '119c5bf883bef42350d52ce5a7927c7c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'AngularRates' 'Thrust' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'angular_rates' 'thrust' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        AngularRates
        Thrust
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'RateThrust', 'Header')
            obj.Header = val;
        end
        function set.AngularRates(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'RateThrust', 'AngularRates')
            obj.AngularRates = val;
        end
        function set.Thrust(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'RateThrust', 'Thrust')
            obj.Thrust = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.RateThrust.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.RateThrust(strObj);
        end
    end
end
