
classdef RollPitchYawrateThrust < ros.Message
    %RollPitchYawrateThrust MATLAB implementation of mav_msgs/RollPitchYawrateThrust
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/RollPitchYawrateThrust' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '10a56a30857affade0889a3662fc2bc9' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Thrust' 'Roll' 'Pitch' 'YawRate' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'thrust' 'roll' 'pitch' 'yaw_rate' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Thrust
        Roll
        Pitch
        YawRate
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'RollPitchYawrateThrust', 'Header')
            obj.Header = val;
        end
        function set.Thrust(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'RollPitchYawrateThrust', 'Thrust')
            obj.Thrust = val;
        end
        function set.Roll(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RollPitchYawrateThrust', 'Roll');
            obj.Roll = double(val);
        end
        function set.Pitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RollPitchYawrateThrust', 'Pitch');
            obj.Pitch = double(val);
        end
        function set.YawRate(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RollPitchYawrateThrust', 'YawRate');
            obj.YawRate = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.RollPitchYawrateThrust.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.RollPitchYawrateThrust(strObj);
        end
    end
end
