
classdef System_pose < ros.Message
    %System_pose MATLAB implementation of mav_msgs/System_pose
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/System_pose' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '3e2775e2865995f470d2e34021ef22e7' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Uav1' 'Uav2' 'Uav3' 'Uav4' 'Payload' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'uav1' 'uav2' 'uav3' 'uav4' 'payload' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.geometry_msgs.Pose' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Uav1
        Uav2
        Uav3
        Uav4
        Payload
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Header')
            obj.Header = val;
        end
        function set.Uav1(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav1')
            obj.Uav1 = val;
        end
        function set.Uav2(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav2')
            obj.Uav2 = val;
        end
        function set.Uav3(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav3')
            obj.Uav3 = val;
        end
        function set.Uav4(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Uav4')
            obj.Uav4 = val;
        end
        function set.Payload(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'System_pose', 'Payload')
            obj.Payload = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.System_pose.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.System_pose(strObj);
        end
    end
end
