# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mav_msgs/System_pose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class System_pose(genpy.Message):
  _md5sum = "3e2775e2865995f470d2e34021ef22e7"
  _type = "mav_msgs/System_pose"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

geometry_msgs/Pose uav1
geometry_msgs/Pose uav2
geometry_msgs/Pose uav3
geometry_msgs/Pose uav4
geometry_msgs/Pose payload


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','uav1','uav2','uav3','uav4','payload']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,uav1,uav2,uav3,uav4,payload

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(System_pose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav1 is None:
        self.uav1 = geometry_msgs.msg.Pose()
      if self.uav2 is None:
        self.uav2 = geometry_msgs.msg.Pose()
      if self.uav3 is None:
        self.uav3 = geometry_msgs.msg.Pose()
      if self.uav4 is None:
        self.uav4 = geometry_msgs.msg.Pose()
      if self.payload is None:
        self.payload = geometry_msgs.msg.Pose()
    else:
      self.header = std_msgs.msg.Header()
      self.uav1 = geometry_msgs.msg.Pose()
      self.uav2 = geometry_msgs.msg.Pose()
      self.uav3 = geometry_msgs.msg.Pose()
      self.uav4 = geometry_msgs.msg.Pose()
      self.payload = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_35d().pack(_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav1 is None:
        self.uav1 = geometry_msgs.msg.Pose()
      if self.uav2 is None:
        self.uav2 = geometry_msgs.msg.Pose()
      if self.uav3 is None:
        self.uav3 = geometry_msgs.msg.Pose()
      if self.uav4 is None:
        self.uav4 = geometry_msgs.msg.Pose()
      if self.payload is None:
        self.payload = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 280
      (_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w,) = _get_struct_35d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_35d().pack(_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav1 is None:
        self.uav1 = geometry_msgs.msg.Pose()
      if self.uav2 is None:
        self.uav2 = geometry_msgs.msg.Pose()
      if self.uav3 is None:
        self.uav3 = geometry_msgs.msg.Pose()
      if self.uav4 is None:
        self.uav4 = geometry_msgs.msg.Pose()
      if self.payload is None:
        self.payload = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 280
      (_x.uav1.position.x, _x.uav1.position.y, _x.uav1.position.z, _x.uav1.orientation.x, _x.uav1.orientation.y, _x.uav1.orientation.z, _x.uav1.orientation.w, _x.uav2.position.x, _x.uav2.position.y, _x.uav2.position.z, _x.uav2.orientation.x, _x.uav2.orientation.y, _x.uav2.orientation.z, _x.uav2.orientation.w, _x.uav3.position.x, _x.uav3.position.y, _x.uav3.position.z, _x.uav3.orientation.x, _x.uav3.orientation.y, _x.uav3.orientation.z, _x.uav3.orientation.w, _x.uav4.position.x, _x.uav4.position.y, _x.uav4.position.z, _x.uav4.orientation.x, _x.uav4.orientation.y, _x.uav4.orientation.z, _x.uav4.orientation.w, _x.payload.position.x, _x.payload.position.y, _x.payload.position.z, _x.payload.orientation.x, _x.payload.orientation.y, _x.payload.orientation.z, _x.payload.orientation.w,) = _get_struct_35d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_35d = None
def _get_struct_35d():
    global _struct_35d
    if _struct_35d is None:
        _struct_35d = struct.Struct("<35d")
    return _struct_35d
