
classdef PolygonWithHolesStamped < ros.Message
    %PolygonWithHolesStamped MATLAB implementation of mav_planning_msgs/PolygonWithHolesStamped
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_planning_msgs/PolygonWithHolesStamped' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '75e2ac63509c016edab7c5a5ed67059b' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Polygon' 'Altitude' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'polygon' 'altitude' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.mav_planning_msgs.PolygonWithHoles' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Polygon
        Altitude
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'PolygonWithHolesStamped', 'Header')
            obj.Header = val;
        end
        function set.Polygon(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.mav_planning_msgs.PolygonWithHoles'};
            validateattributes(val, validClasses, validAttributes, 'PolygonWithHolesStamped', 'Polygon')
            obj.Polygon = val;
        end
        function set.Altitude(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolygonWithHolesStamped', 'Altitude');
            obj.Altitude = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_planning_msgs.PolygonWithHolesStamped.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_planning_msgs.PolygonWithHolesStamped(strObj);
        end
    end
end
