
classdef TorqueThrust < ros.Message
    %TorqueThrust MATLAB implementation of mav_msgs/TorqueThrust
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/TorqueThrust' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '81293743ae52683b61e39c21bc0b30db' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Torque' 'Thrust' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'torque' 'thrust' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Torque
        Thrust
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'TorqueThrust', 'Header')
            obj.Header = val;
        end
        function set.Torque(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'TorqueThrust', 'Torque')
            obj.Torque = val;
        end
        function set.Thrust(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'TorqueThrust', 'Thrust')
            obj.Thrust = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.TorqueThrust.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.TorqueThrust(strObj);
        end
    end
end
