
classdef StartStopTask < ros.Message
    %StartStopTask MATLAB implementation of mav_state_machine_msgs/StartStopTask
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_state_machine_msgs/StartStopTask' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '10cd1c89cea1d199a1d9752c42bc712c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'TaskName' 'Start' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'task_name' 'start' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        TaskName
        Start
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'StartStopTask', 'Header')
            obj.Header = val;
        end
        function set.TaskName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'StartStopTask', 'TaskName');
            obj.TaskName = char(val);
        end
        function set.Start(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'StartStopTask', 'Start');
            obj.Start = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_state_machine_msgs.StartStopTask.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_state_machine_msgs.StartStopTask(strObj);
        end
    end
end
