
classdef RunTaskServiceRequest < ros.Message
    %RunTaskServiceRequest MATLAB implementation of mav_state_machine_msgs/RunTaskServiceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_state_machine_msgs/RunTaskServiceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '78def82808ce5580c326beaff29b4920' % The MD5 Checksum of the message definition
        PropertyList = { 'TaskName' 'Start' } % List of non-constant message properties
        ROSPropertyList = { 'task_name' 'start' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        TaskName
        Start
    end
    methods
        function set.TaskName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RunTaskServiceRequest', 'TaskName');
            obj.TaskName = char(val);
        end
        function set.Start(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RunTaskServiceRequest', 'Start');
            obj.Start = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_state_machine_msgs.RunTaskServiceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_state_machine_msgs.RunTaskServiceRequest(strObj);
        end
    end
end
