
classdef AttitudeThrust < ros.Message
    %AttitudeThrust MATLAB implementation of mav_msgs/AttitudeThrust
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/AttitudeThrust' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7cee443b02735e42bda0ad5910302718' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Attitude' 'Thrust' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'attitude' 'thrust' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msg.geometry_msgs.Quaternion' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Attitude
        Thrust
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'AttitudeThrust', 'Header')
            obj.Header = val;
        end
        function set.Attitude(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.geometry_msgs.Quaternion'};
            validateattributes(val, validClasses, validAttributes, 'AttitudeThrust', 'Attitude')
            obj.Attitude = val;
        end
        function set.Thrust(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'AttitudeThrust', 'Thrust')
            obj.Thrust = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.AttitudeThrust.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.AttitudeThrust(strObj);
        end
    end
end
