
classdef Actuators < ros.Message
    %Actuators MATLAB implementation of mav_msgs/Actuators
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_msgs/Actuators' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '25741daf38ed25442e3a66a855ee8d9c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Angles' 'AngularVelocities' 'Normalized' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'angles' 'angular_velocities' 'normalized' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Angles
        AngularVelocities
        Normalized
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'Actuators', 'Header')
            obj.Header = val;
        end
        function set.Angles(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'Actuators', 'Angles');
            obj.Angles = double(val);
        end
        function set.AngularVelocities(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'Actuators', 'AngularVelocities');
            obj.AngularVelocities = double(val);
        end
        function set.Normalized(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'Actuators', 'Normalized');
            obj.Normalized = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_msgs.Actuators.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_msgs.Actuators(strObj);
        end
    end
end
