
classdef CpuInfo < ros.Message
    %CpuInfo MATLAB implementation of mav_system_msgs/CpuInfo
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_system_msgs/CpuInfo' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd955ed6c182adaafbfa41e78710954d2' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'HeaviestProcesses' 'CpuPercent' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'heaviest_processes' 'cpu_percent' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.mav_system_msgs.ProcessInfo' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        HeaviestProcesses
        CpuPercent
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'CpuInfo', 'Header')
            obj.Header = val;
        end
        function set.HeaviestProcesses(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.mav_system_msgs.ProcessInfo.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.mav_system_msgs.ProcessInfo'};
            validateattributes(val, validClasses, validAttributes, 'CpuInfo', 'HeaviestProcesses')
            obj.HeaviestProcesses = val;
        end
        function set.CpuPercent(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'CpuInfo', 'CpuPercent');
            obj.CpuPercent = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_system_msgs.CpuInfo.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_system_msgs.CpuInfo(strObj);
        end
    end
end
