
classdef PolynomialTrajectory < ros.Message
    %PolynomialTrajectory MATLAB implementation of mav_planning_msgs/PolynomialTrajectory
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_planning_msgs/PolynomialTrajectory' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2daf5d705534e84f80980f4673a0e62b' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Segments' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'segments' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.mav_planning_msgs.PolynomialSegment' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Segments
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'Header')
            obj.Header = val;
        end
        function set.Segments(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.mav_planning_msgs.PolynomialSegment.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.mav_planning_msgs.PolynomialSegment'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'Segments')
            obj.Segments = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_planning_msgs.PolynomialTrajectory.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_planning_msgs.PolynomialTrajectory(strObj);
        end
    end
end
