
classdef PlannerServiceResponse < ros.Message
    %PlannerServiceResponse MATLAB implementation of mav_planning_msgs/PlannerServiceResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mav_planning_msgs/PlannerServiceResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2dfc73ed0482f368aa016a76f49c8aed' % The MD5 Checksum of the message definition
        PropertyList = { 'PolynomialPlan' 'PolynomialPlan4D' 'SampledPlan' 'Success' } % List of non-constant message properties
        ROSPropertyList = { 'polynomial_plan' 'polynomial_plan_4D' 'sampled_plan' 'success' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.mav_planning_msgs.PolynomialTrajectory' ...
            'ros.msggen.mav_planning_msgs.PolynomialTrajectory4D' ...
            'ros.msggen.trajectory_msgs.MultiDOFJointTrajectory' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        PolynomialPlan
        PolynomialPlan4D
        SampledPlan
        Success
    end
    methods
        function set.PolynomialPlan(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.mav_planning_msgs.PolynomialTrajectory'};
            validateattributes(val, validClasses, validAttributes, 'PlannerServiceResponse', 'PolynomialPlan')
            obj.PolynomialPlan = val;
        end
        function set.PolynomialPlan4D(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.mav_planning_msgs.PolynomialTrajectory4D'};
            validateattributes(val, validClasses, validAttributes, 'PlannerServiceResponse', 'PolynomialPlan4D')
            obj.PolynomialPlan4D = val;
        end
        function set.SampledPlan(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.trajectory_msgs.MultiDOFJointTrajectory'};
            validateattributes(val, validClasses, validAttributes, 'PlannerServiceResponse', 'SampledPlan')
            obj.SampledPlan = val;
        end
        function set.Success(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PlannerServiceResponse', 'Success');
            obj.Success = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mav_planning_msgs.PlannerServiceResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mav_planning_msgs.PlannerServiceResponse(strObj);
        end
    end
end
